plugins {
    id 'net.fabricmc.fabric-loom' version '1.18.3'
    id 'maven-publish'
    id 'java'
}

configurations.all {
    resolutionStrategy {
        force 'com.google.code.gson:gson:2.10.1'
    }
}

version = project.mod_version
group = project.mod_group_id

base {
    archivesName = project.mod_id
}

repositories {
    mavenCentral()
    maven { url 'https://maven.fabricmc.net/' }
}


dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
    inputs.property "version", project.version
    filteringCharset "UTF-8"
    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}" }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}
