org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=26.3
loader_version=0.19.5
fabric_api_version=0.162.0+26.3

mod_id=bulktrade
mod_name=Bulk Villager Trading
mod_license=MIT
mod_version=1.1.0
mod_group_id=computer.brads.bulktrade
mod_authors=bradcarnage
mod_description=Bulk Villager Trading.\nAutomatically Re-Stocks the trade UI after shift-click.
